### ISSUE TITLE
NodeJS-SDK: Runnable examples

### ISSUE THREAD

**Issue by rasmus-kirk** [Concordium/concordium-node-sdk-js#153]
**Sub-tasks**
- [x] `docs/gRPC.md`
    - [x] Create examples 
    - [x] Test examples
    - [x] Pass review
- [x] `packages/common/README.md`
    - [x] Create examples 
    - [x] Test examples
    - [x] Pass review
- [x] Update documentation
    - [x] Setup typedoc
    - [x] Integrate current docs to typedoc
    - [x] Look into inlining examples in docs ([See this](https://github.com/krisztianb/typedoc-plugin-replace-text/issues/4#issuecomment-1549929121))
    - [x] Add a typedoc pipeline

**Example list**
client #164 
  - [x] banPeer.ts
  - [x] dumpStart.ts
  - [x] dumpStop.ts
  - [x] getAccountInfo.ts
  - [x] getAccountList.ts
  - [x] getAccountNonFinalizedTransactions.ts
  - [x] getAncestors.ts
  - [x] getAnonymityRevokers.ts
  - [x] getBakerList.ts
  - [x] getBannedPeers.ts
  - [x] getBlockChainParameters.ts
  - [x] getBlockFinalizationSummary.ts
  - [x] getBlockInfo.ts
  - [x] getBlockItemStatus.ts
  - [x] getBlockPendingUpdates.ts
  - [x] getBlocksAtHeight.ts
  - [x] getBlockSpecialEvents.ts
  - [x] getBlocks.ts
  - [x] getBlockTransactionEvents.ts
  - [x] getBranches.ts
  - [x] getConsensusStatus.ts
  - [x] getCryptographicParameters.ts
  - [x] getElectionInfo.ts
  - [x] getFinalizedBlocks.ts
  - [x] getIdentityProviders.ts
  - [x] getInstanceInfo.ts
  - [x] getInstanceState.ts
  - [x] getModuleList.ts
  - [x] getModuleSource.ts
  - [x] getNextAccountSequenceNumber.ts
  - [x] getNextUpdateSequenceNumbers.ts
  - [x] getNodeInfo.ts
  - [x] getPassiveDelegationInfo.ts
  - [x] getPassiveDelegatorsRewardPeriod.ts
  - [x] getPassiveDelegators.ts
  - [x] getPeersInfo.ts
  - [x] getPoolDelegatorsRewardPeriod.ts
  - [x] getPoolDelegators.ts
  - [x] getPoolInfo.ts
  - [x] getTokenomicsInfo.ts
  - [x] instanceStateLookup.ts
  - [x] invokeContract.ts
  - [x] peerConnect.ts
  - [x] peerDisconnect.ts
  - [x] shutdown.ts
  - [x] unbanPeer.ts
  - [x] waitForTransactionFinalization.ts

common: #193 
- [x] `aliases.ts`
- [x] `bakerAdd.ts`
- [x] `bakerRemove.ts`
- [x] `delegationAdd.ts`
- [x] `delegationRemove.ts`
- [x] `deployModule.ts`
- [x] `simpleTransfer.ts`
- [x] `statements.ts`
- [x] `streamToList.ts`

composed examples: #194 
- [x] `findAccountCreationBlock.ts`
- [x] `initAndUpdateContract.ts`
- [x] `listAccountCreation.ts`
- [x] `listInitialAccounts.ts`
- [x] `listNumberAccountTransactions.ts`

See Epic #152
