### ISSUE TITLE
Remove deprecated JSON RPC client

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-node-sdk-js#212]
**Task description**
The `JsonRpcClient` has been marked deprecated since the release of the gRPC v2 API of the node. Currently, we translate all types from the gRPC v2 API to their gRPC v1 API correspondants. If we could remove the need to support the first version we could make the code base easier to maintain.

Obviously, these changes will be breaking, and should be scheduled with a major release.

**Clarifications**
- [x] Is there any reason to still keep the JSON RPC client? Do we need to keep supporting the GRPCv1 API?

**Sub-tasks**
- [x] Remove `JsonRpcClient` and types only associated with this
- [x] Change top-level types versioned by different protocol versions to explicitly state a version
  - ~~We could even try to eliminate type translations altogether, and just use the generated GRPC types. Only issue with this is that the generated types seem to be all optional, where in reality they're not. What we could do here is simply override the optional properties in question with required ones.~~
    - Not doing this, as it will decrease developer experience (types are worse) and will cause a lot of breaking changes, requiring a lot of changes in our own consumers of the SDK.
  - [x] `ChainParameters`
  - [x] `ElectionInfo`
  - [x] `BlockInfo`
  - [x] `ConsensusStatus`

**From #135**
  - [ ]  ~~Remove TransactionSummaryType~~
  - [x] Update delegatorId fields in event data to be bigints
  - [x] chainParameters.foundationAccount should not be optional

**Comment by rasmus-kirk** [comment]
See also #135

**Comment by abizjak** [comment]
Regarding the need, the main issue is legacy dApps that use it, which I think includes our bridge.

But that means the service, not the SDK itself.

What we discussed today was that we will disable V1 API in the nodes (by default, people can still enable it) in all our distributions for node version 6 release.

And then remove it some time in Q4.

**Comment by abizjak** [comment]
Does the wallet still expose a JSON-RPC client?

**Comment by soerenbf** [comment]
> Does the wallet still expose a JSON-RPC client?

Yes, it does

**Comment by soerenbf** [comment]
> **From #135**
> 
> * [ ]   Remove TransactionSummaryType

@rasmus-kirk I don't understand why we should remove this? Don't we need some way to discriminate between the different transaction types (or block item summaries)?

**Comment by rasmus-kirk** [comment]
> > **From #135**
> > 
> > * [ ]    Remove TransactionSummaryType
> 
> @rasmus-kirk I don't understand why we should remove this? Don't we need some way to discriminate between the different transaction types (or block item summaries)?

Not sure what the original intention of that todo was. Looking at it, I don't see anything wrong with what we're doing now. Maybe I misunderstood something back when I added it, or whatever bothered me at the time was improved/fixed :shrug:

I think you can just cross it off/remove it.
