### ISSUE TITLE
Support GRPC changes for the new consensus

### ISSUE THREAD

**Issue by rasmus-kirk** [Concordium/concordium-node-sdk-js#240]
**Sub-tasks**
- [x] `getBakersRewardPeriod`: gets the bakers and finalizers that are current for the reward period of a given block. [#239](https://github.com/Concordium/concordium-node-sdk-js/pull/239) 
- [ ] `getWinningBakersEpoch`: gets the bakers that won rounds in the given (past) epoch.
- [x] `getBakerEarliestWinTime`: gets the projected earliest time that a baker may be required to produce a block. [#239](https://github.com/Concordium/concordium-node-sdk-js/pull/239) 
- [x] `getBlockCertificates`: get the quorum certificate, timeout certificate and epoch finalization entry present in a block. [#239](https://github.com/Concordium/concordium-node-sdk-js/pull/239) 
- [ ] `getFirstBlockEpoch`: get the block hash of the first finalized block in a given epoch.

Following changes to current endpoints:
- [x] `getPoolInfo` is amended to add the commission rates for the current reward period to the result. [#239](https://github.com/Concordium/concordium-node-sdk-js/pull/239) 

**Related subissues:**
#232 
#234 
#235
