### ISSUE TITLE
Add new events and entrypoint related to V1 smart contracts

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node-sdk-js#31]
**Task description**

There are some minor changes related to the sync-calls smart contracts features.

- [ ] V1 smart contracts add two new events (interrupted and resumed) that should be handled in the SDK.
- [ ] Additionally there is a new entrypoint "InvokeContract" that should be added.
- [x] In relation to the previous point, GetInstanceInfo response is now versioned, and V1 does not contain the "model" field.

**Comment by shjortConcordium** [comment]
`InvokeContract` and the new events have been added in the 1.1.0 version.
(`GetInstanceInfo` became versioned in 1.0.0)
