### ISSUE TITLE
Fully support delegation update

### ISSUE THREAD

**Issue by shjortConcordium** [Concordium/concordium-node-sdk-js#38]
**Task description**
Work has already been done to support the delegation update (Protocol update 4), https://github.com/Concordium/concordium-node-sdk-js/pull/35, but we should ensure that the SDK fully supports the update.

**Sub-tasks**
- [x] Ensure that types on client calls are updated/versioned
- [ ] Add new transaction event types
- [ ] Anything else that should be done
